@echo off
Title Coin-Miner
Timeout 15 /nobreak >nul
cls



:loop
PING google.com -n 1 -w 1000 | FIND "time=" > NUL
IF ERRORLEVEL 1 goto loop 
Timeout 5 /nobreak >nul
cls


Echo    Coin-miner
timeout 3 /nobreak >nul
Echo             Made by Remix#2929
timeout 5 /nobreak >nul
cls

echo By the way, It takes some time to share/tranfer the coins
Echo so you have to wait 40s for Each Batch
timeout 5 /nobreak >nul
cls

:no
@echo off
echo ok ok Let's start the miner
Timeout 5 /nobreak >nul
cls

echo Also, Please don't skip the timer
timeout 4 /nobreak >nul
cls

echo The miner will start in 5...
Timeout 1 /nobreak >nul
cls

echo The miner will start in 4...
Timeout 1 /nobreak >nul
cls

echo The miner will start in 3...
Timeout 1 /nobreak >nul
cls

echo The miner will start in 2...
Timeout 1 /nobreak >nul
cls

echo The miner will start in 1...
Timeout 1 /nobreak >nul
cls

echo The miner will start in 0...
Timeout 1 /nobreak >nul
cls


@echo on
cls
start https://discord.com/channels/711399169893466133/809500159574540338
Timeout 5

start https://discord.com/channels/711399169893466133/820815163518484542
Timeout 5

start https://discord.com/channels/711399169893466133/820815208703721523
Timeout 5

start https://discord.com/channels/711399169893466133/820816756623802418
Timeout 5

start https://discord.com/channels/711399169893466133/821633510400851999
Timeout 5

start https://discord.com/channels/711399169893466133/820816882264440893
Timeout 5

timeout 5
Goto dawasd
  ___________________________________________________________________________________________
 |----------------------------------------| Beg |--------------------------------------------|

:dawasd
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^1" & script.vbs
Timeout 2

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls beg" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 46

goto 777
:778
goto 779
:770

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^1" & script.vbs
Timeout 2

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls beg" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 46

goto 777a
:778a
goto 779a
:770a

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^1" & script.vbs
Timeout 2

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls beg" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 46

goto 777b
:778b
goto 779b
:770b

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^1" & script.vbs
Timeout 2

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls beg" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 46

goto 777c
:778c
goto 779c
:770c

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^1" & script.vbs
Timeout 2

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls beg" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 46

goto 777d
:778d
goto 779d
:770d

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^1" & script.vbs
Timeout 2

Goto Fish-Seller
:Fishy
Goto Hunt-Seller
:Hunter
Timeout 10
Goto POLPOL

  _____________________________________________________________________________________________________
 |----------------------------------------| Money dropper |--------------------------------------------|

:POLPOL
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^6" & script.vbs
Timeout 2

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls share all Remix#2929" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
Timeout 5




goto dawasd




  _____________________________________________________________________________________________________
 |-----------------------|Scripts  (Not in use(Might be deleted in next update|------------------------|

:yes
start https://discord.com/channels/711399169893466133/809527139174340332

timeout 5

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls daily" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 5 /nobreak >nul
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls monthly" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
cls

taskkill /IM chrome.exe >nul /f

goto no



echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Fish" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Hunt" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs


echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls gift banknotes all remix" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
Timeout 5




  ______________________________________________________________________________________________________________
 |------------------------------------------| Item tradeing (Not in use yet) |---------------------------------------------------|   

                                          (I.N.H) -Item Name Here

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "Pls gift remix (I.N.H) " & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs






  ______________________________________________________________________________________________________________
 |----------------------------------------------| Fish/Hunt |---------------------------------------------------|



:777
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^2" & script.vbs
Timeout 4

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Fish" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "." & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 2
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{UP}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{BACKSPACE}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

Timeout 5

GOTO 778

:779
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^3" & script.vbs
Timeout 4

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls hunt" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "." & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 2
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{UP}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{BACKSPACE}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs


Timeout 10


Goto 770

:777a
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^2" & script.vbs
Timeout 2

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Fish" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs


timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "." & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 2
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{UP}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{BACKSPACE}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

Timeout 5

GOTO 778a

:779a
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^3" & script.vbs
Timeout 2

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls hunt" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "." & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 2
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{UP}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{BACKSPACE}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

Timeout 5

Goto 770a




:777b
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^2" & script.vbs
Timeout 2

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Fish" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "." & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 2
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{UP}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{BACKSPACE}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs


Timeout 5

GOTO 778b

:779b
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^3" & script.vbs
Timeout 2

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls hunt" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "." & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 2
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{UP}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{BACKSPACE}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs


Timeout 5

Goto 770b




:777c
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^2" & script.vbs
Timeout 2

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Fish" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "." & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 2
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{UP}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{BACKSPACE}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

Timeout 5

GOTO 778c

:779c
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^3" & script.vbs
Timeout 2

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls hunt" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "." & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 2
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{UP}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{BACKSPACE}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs


Timeout 5

Goto 770c




:777d
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^2" & script.vbs
Timeout 2

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Fish" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "." & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 2
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{UP}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{BACKSPACE}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

Timeout 5

GOTO 778d

:779d
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^3" & script.vbs
Timeout 2

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls hunt" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "." & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 2
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{UP}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{BACKSPACE}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
timeout 0
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs


Timeout 5

Goto 770d











  ________________________________________________________________________________________________________
 |----------------------------------------| Fish/Hunt-Seller |--------------------------------------------|
              
   |\  ___   O 
   | \/  0\ o   
   |      <    <FISH SELLER)
   | /\___/
   |/


:Fish-Seller
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^4" & script.vbs
Timeout 4
Timeout 10

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Sell Fish all" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
Timeout 3

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Sell rarefish all" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
Timeout 3

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Sell ExoticFish all" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs


Timeout 5
Goto Fishy

:Hunt-Seller
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "^5" & script.vbs
Timeout 4

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Sell Deer all" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
Timeout 3

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Sell skunk all" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
Timeout 3

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Sell Duck all" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
Timeout 3

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Sell Rabbit all" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs
Timeout 3

echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "pls Sell Boar all" & script.vbs
echo >script.vbs set shell = CreateObject("WScript.Shell"):shell.SendKeys "{ENTER}" & script.vbs

Timeout 3

goto Hunter








  ____________________________________________________________________________________________________
 |----------------------------------------| Note-to-self |--------------------------------------------|

  Channels Numbers/Names

 -Coin-miner
 https://discord.com/channels/711399169893466133/809500159574540338 -1

 -Fish-Miner
 https://discord.com/channels/711399169893466133/820815163518484542 -2

 -hunt-miner
 https://discord.com/channels/711399169893466133/820815208703721523 -3

 -Fish-seller
 https://discord.com/channels/711399169893466133/820816756623802418 -4

 -hunt-seller
 https://discord.com/channels/711399169893466133/821633510400851999 -5

 -income-channel
 https://discord.com/channels/711399169893466133/820816882264440893 -6

 -All-in-one
 https://discord.com/channels/711399169893466133/821521830992150538 -7

 




